author: The Machine Intelligence and Pattern Analysis Laboratory (MiPal) Griffith University
theme: fullwidth
github_url: https://github.com/mipalgu/GUUI
github_file_prefix: https://github.com/mipalgu/GUUI/tree/main
root_url: https://mipalgu.github.io/GUUI/
min_acl: private
