name: Windows Latest Swift CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:

  exec-windows-ci:
    runs-on: windows-latest

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
            branch: swift-5.6.2-release
            tag: 5.6.2-RELEASE

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Debug Build
        shell: pwsh
        run: swift build -c debug

      - name: Release build
        shell: pwsh
        run: swift build -c release

      - name: Debug Test
        shell: pwsh
        run: swift test

      - name: Release Test
        shell: pwsh
        run: swift test -c release

